import "server-only";

import type { PoolClient } from "pg";
import type { PatientLanguage } from "@/lib/patient-flow";
import {
  canTransitionCaseStatus,
  caseStatusOnCompletion,
  type CaseStatus,
} from "@/lib/case-status";
import type {
  ConsentStatus,
  PatientStep,
} from "@/lib/patient-flow";
import { writeAudit } from "./audit";

export type CaseRecord = {
  id: string;
  caseNo: number;
  caseId: string;
  ownerId: string;
  status: "ACTIVE" | "EXPIRED" | "COMPLETED";
  caseStatus: CaseStatus;
  language: PatientLanguage;
  consentStatus: ConsentStatus;
  consentVersion: string | null;
  consentTimestamp: Date | null;
  workflowStep: PatientStep;
  complaintText: string | null;
  bodyRegion: string | null;
  bodySubregion: string | null;
  interviewData: Record<string, unknown> | null;
  demoFlag: boolean;
  cancellationReason: string | null;
  summary: Record<string, unknown> | null;
  createdAt: Date;
  updatedAt: Date;
  expiresAt: Date;
  completedAt: Date | null;
};

const caseColumns = `id, case_no, case_id, owner_id, status, case_status, language,
  consent_status, consent_version, consent_timestamp, workflow_step,
  complaint_text, body_region, body_subregion, interview_data, demo_flag,
  cancellation_reason, summary, created_at, updated_at, expires_at, completed_at`;

function toCaseRecord(row: Record<string, unknown>): CaseRecord {
  return {
    id: row.id as string,
    caseNo: row.case_no as number,
    caseId: row.case_id as string,
    ownerId: row.owner_id as string,
    status: row.status as CaseRecord["status"],
    caseStatus: row.case_status as CaseStatus,
    language: row.language as PatientLanguage,
    consentStatus: row.consent_status as ConsentStatus,
    consentVersion: row.consent_version as string | null,
    consentTimestamp: (row.consent_timestamp as Date | null) ?? null,
    workflowStep: row.workflow_step as PatientStep,
    complaintText: row.complaint_text as string | null,
    bodyRegion: row.body_region as string | null,
    bodySubregion: row.body_subregion as string | null,
    interviewData: row.interview_data as Record<string, unknown> | null,
    demoFlag: row.demo_flag as boolean,
    cancellationReason: row.cancellation_reason as string | null,
    summary: row.summary as Record<string, unknown> | null,
    createdAt: row.created_at as Date,
    updatedAt: row.updated_at as Date,
    expiresAt: row.expires_at as Date,
    completedAt: row.completed_at as Date | null,
  };
}

export type CaseUpdate = {
  language?: PatientLanguage;
  consentStatus?: ConsentStatus;
  workflowStep?: PatientStep;
  complaintText?: string | null;
  bodyRegion?: string | null;
  bodySubregion?: string | null;
  interviewData?: Record<string, unknown> | null;
  demoFlag?: boolean;
};

const consentVersion = "phase-2-v1";

/**
 * Create a patient case (kiosk session). Runs inside withNewSessionTx so the
 * RLS policy admits the insert via the server-generated owner id. `ownerUuid`
 * is generated by the caller (server-side) and is NOT sent by the browser.
 */
export async function createCase(
  client: PoolClient,
  params: {
    ownerUuid: string;
    idempotencyKey: string;
    language: PatientLanguage;
    demoFlag?: boolean;
  },
): Promise<CaseRecord> {
  const existing = await client.query(
    `SELECT ${caseColumns} FROM patient_sessions WHERE idempotency_key = $1`,
    [params.idempotencyKey],
  );
  if (existing.rows.length > 0) {
    return toCaseRecord(existing.rows[0]);
  }

  const inserted = await client.query(
    `INSERT INTO patient_sessions
       (owner_id, idempotency_key, language, demo_flag, case_no)
     VALUES ($1, $2, $3, $4, (SELECT COALESCE(MAX(case_no), 0) + 1 FROM patient_sessions))
     RETURNING ${caseColumns}`,
    [params.ownerUuid, params.idempotencyKey, params.language, params.demoFlag ?? false],
  );
  await writeAudit(client, { type: "PATIENT", id: inserted.rows[0].id }, "case.created", {
    type: "case",
    id: inserted.rows[0].case_id,
  });
  return toCaseRecord(inserted.rows[0]);
}

export async function getCase(
  client: PoolClient,
  sessionId: string,
): Promise<CaseRecord | null> {
  const result = await client.query(`SELECT ${caseColumns} FROM patient_sessions WHERE id = $1`, [sessionId]);
  return result.rows.length > 0 ? toCaseRecord(result.rows[0]) : null;
}

export async function updateCase(
  client: PoolClient,
  sessionId: string,
  changes: CaseUpdate,
): Promise<CaseRecord | null> {
  const sets: string[] = [];
  const values: unknown[] = [];
  if (changes.language !== undefined) {
    sets.push(`language = $${values.push(changes.language)}`);
  }
  if (changes.consentStatus !== undefined) {
    sets.push(`consent_status = $${values.push(changes.consentStatus)}`);
    sets.push(`consent_version = $${values.push(changes.consentStatus === "NOT_REVIEWED" ? null : consentVersion)}`);
    sets.push(`consent_timestamp = $${values.push(changes.consentStatus === "NOT_REVIEWED" ? null : new Date().toISOString())}`);
  }
  if (changes.workflowStep !== undefined) {
    sets.push(`workflow_step = $${values.push(changes.workflowStep)}`);
  }
  if (changes.complaintText !== undefined) {
    sets.push(`complaint_text = $${values.push(changes.complaintText)}`);
  }
  if (changes.bodyRegion !== undefined) {
    sets.push(`body_region = $${values.push(changes.bodyRegion)}`);
  }
  if (changes.bodySubregion !== undefined) {
    sets.push(`body_subregion = $${values.push(changes.bodySubregion)}`);
  }
  if (changes.interviewData !== undefined) {
    sets.push(`interview_data = $${values.push(changes.interviewData)}`);
  }
  if (changes.demoFlag !== undefined) {
    sets.push(`demo_flag = $${values.push(changes.demoFlag)}`);
  }
  if (sets.length === 0) return getCase(client, sessionId);
  values.push(sessionId);
  const result = await client.query(
    `UPDATE patient_sessions SET ${sets.join(", ")} WHERE id = $${values.length} RETURNING ${caseColumns}`,
    values,
  );
  return result.rows.length > 0 ? toCaseRecord(result.rows[0]) : null;
}

/** Transition the case workflow status with validation + audit. */
export async function transitionCase(
  client: PoolClient,
  sessionId: string,
  next: CaseStatus,
  actor: { type: "PATIENT" | "STAFF" | "SYSTEM"; id?: string },
  detail: Record<string, unknown> = {},
): Promise<CaseRecord | null> {
  const current = await getCase(client, sessionId);
  if (!current) return null;
  if (current.caseStatus === next) return current;
  if (!canTransitionCaseStatus(current.caseStatus, next)) {
    throw new Error(`Invalid case status transition: ${current.caseStatus} -> ${next}`);
  }
  const extra: string[] = [];
  const values: unknown[] = [];
  if (next === "COMPLETED") {
    extra.push(`completed_at = $${values.push(new Date().toISOString())}`);
  }
  const sql = `UPDATE patient_sessions SET case_status = $1${extra.length ? `, ${extra.join(", ")}` : ""}
               WHERE id = $${values.length + 2} RETURNING ${caseColumns}`;
  const result = await client.query(sql, [next, ...values, sessionId]);
  if (result.rows.length === 0) return null;
  await writeAudit(client, actor, `case.${next.toLowerCase()}`, { type: "case", id: current.caseId }, detail);
  return toCaseRecord(result.rows[0]);
}

/** Mark the case complete (kiosk journey finished) with the canonical status. */
export async function completeKioskIntake(
  client: PoolClient,
  sessionId: string,
  hasUnreviewedSignals: boolean,
  summary: Record<string, unknown>,
): Promise<CaseRecord | null> {
  const target = caseStatusOnCompletion(hasUnreviewedSignals);
  const sets = [`case_status = $1`, `summary = $2`, `completed_at = $3`];
  const result = await client.query(
    `UPDATE patient_sessions SET ${sets.join(", ")} WHERE id = $4 AND status = 'ACTIVE' RETURNING ${caseColumns}`,
    [target, JSON.stringify(summary), new Date().toISOString(), sessionId],
  );
  if (result.rows.length === 0) return null;
  await writeAudit(client, { type: "PATIENT", id: sessionId }, `case.${target.toLowerCase()}`, {
    type: "case",
    id: result.rows[0].case_id,
  });
  return toCaseRecord(result.rows[0]);
}

/** Complete the session lifecycle (kiosk hand-off / reset). */
export async function closeSessionLifecycle(
  client: PoolClient,
  sessionId: string,
  actor: { type: "PATIENT" | "STAFF" | "SYSTEM"; id?: string },
): Promise<void> {
  await client.query(
    `UPDATE patient_sessions SET status = 'COMPLETED', completed_at = COALESCE(completed_at, now())
     WHERE id = $1 AND status = 'ACTIVE'`,
    [sessionId],
  );
  await writeAudit(client, actor, "session.completed", { type: "case", id: sessionId });
}

// ---------------------------------------------------------------------------
// Staff views
// ---------------------------------------------------------------------------

export type QueueCase = {
  caseId: string;
  sessionId: string;
  caseStatus: CaseStatus;
  language: PatientLanguage;
  primaryComplaint: string | null;
  complaintCount: number;
  topSeverity: string | null;
  unreviewedSignals: number;
  documentCount: number;
  documentsProcessing: number;
  demoFlag: boolean;
  createdAt: Date;
  completedAt: Date | null;
  startedAt: Date | null;
  doctorName: string | null;
};

/**
 * Queue list for doctor/hospital consoles, derived from real state:
 * complaints, safety signals, and documents are all counted live.
 */
export async function listQueueCases(client: PoolClient): Promise<QueueCase[]> {
  const result = await client.query(`
    SELECT s.id, s.case_id, s.case_status, s.language, s.demo_flag, s.created_at, s.completed_at,
           con.started_at AS consult_started_at, c.display_name AS doctor_name,
           (SELECT co.complaint_text FROM complaints co
             WHERE co.session_id = s.id AND co.status = 'ACTIVE'
             ORDER BY co.position LIMIT 1) AS primary_complaint,
           (SELECT COUNT(*)::int FROM complaints co
             WHERE co.session_id = s.id AND co.status = 'ACTIVE') AS complaint_count,
           (SELECT co.severity FROM complaints co
             WHERE co.session_id = s.id AND co.status = 'ACTIVE' AND co.severity IS NOT NULL
             ORDER BY CASE co.severity WHEN 'MILD' THEN 1 WHEN 'MODERATE' THEN 2
                       WHEN 'SEVERE' THEN 3 ELSE 4 END DESC LIMIT 1) AS top_severity,
           (SELECT COUNT(*)::int FROM safety_signals sg
             WHERE sg.session_id = s.id AND sg.status = 'UNREVIEWED') AS unreviewed_signals,
           (SELECT COUNT(*)::int FROM documents d WHERE d.session_id = s.id) AS document_count,
           (SELECT COUNT(*)::int FROM documents d WHERE d.session_id = s.id
             AND d.ocr_status IN ('PENDING', 'PROCESSING')
             OR d.session_id = s.id AND d.extraction_status = 'PROCESSING') AS documents_processing
      FROM patient_sessions s
      LEFT JOIN consultations con ON con.session_id = s.id AND con.status = 'IN_PROGRESS'
      LEFT JOIN staff c ON c.id = con.doctor_id
     WHERE s.case_status IN ('AWAITING_REVIEW', 'URGENT_REVIEW', 'IN_CONSULTATION', 'IN_PROGRESS', 'NEW')
     ORDER BY
       CASE WHEN s.case_status = 'URGENT_REVIEW' THEN 0
            WHEN s.case_status = 'AWAITING_REVIEW' THEN 1
            WHEN s.case_status = 'IN_CONSULTATION' THEN 2 ELSE 3 END,
       s.created_at`);
  return result.rows.map((row) => ({
    caseId: row.case_id as string,
    sessionId: row.id as string,
    caseStatus: row.case_status as CaseStatus,
    language: row.language as PatientLanguage,
    primaryComplaint: row.primary_complaint as string | null,
    complaintCount: row.complaint_count as number,
    topSeverity: row.top_severity as string | null,
    unreviewedSignals: row.unreviewed_signals as number,
    documentCount: row.document_count as number,
    documentsProcessing: row.documents_processing as number,
    demoFlag: row.demo_flag as boolean,
    createdAt: row.created_at as Date,
    completedAt: row.completed_at as Date | null,
    startedAt: row.consult_started_at as Date | null,
    doctorName: row.doctor_name as string | null,
  }));
}

/** Operational funnel counts (hospital console) — all live SQL aggregates. */
export async function getFunnelCounts(client: PoolClient) {
  const result = await client.query(`
    SELECT
      (SELECT COUNT(*)::int FROM patient_sessions WHERE case_status = 'NEW' OR case_status = 'IN_PROGRESS') AS kiosk_intake,
      (SELECT COUNT(*)::int FROM patient_sessions WHERE case_status = 'AWAITING_REVIEW' OR case_status = 'URGENT_REVIEW') AS pre_consultation,
      (SELECT COUNT(*)::int FROM documents WHERE ocr_status IN ('PENDING','PROCESSING')
         OR extraction_status = 'PROCESSING') AS document_processing,
      (SELECT COUNT(*)::int FROM patient_sessions WHERE case_status = 'IN_CONSULTATION') AS in_consultation,
      (SELECT COUNT(*)::int FROM patient_sessions WHERE case_status = 'COMPLETED') AS completed,
      (SELECT COUNT(*)::int FROM patient_sessions WHERE case_status = 'URGENT_REVIEW') AS urgent,
      (SELECT COALESCE(AVG(EXTRACT(EPOCH FROM (now() - created_at)))::bigint, 0)
         FROM patient_sessions WHERE case_status IN ('AWAITING_REVIEW','URGENT_REVIEW'))::int AS avg_wait_seconds`);
  return result.rows[0] as {
    kiosk_intake: number;
    pre_consultation: number;
    document_processing: number;
    in_consultation: number;
    completed: number;
    urgent: number;
    avg_wait_seconds: number;
  };
}
