import { NextResponse } from "next/server";import { getActiveKioskSession,patientWritable } from "@/lib/db/session-scope";import { withKioskTx } from "@/lib/db/pool";import { extractEvidence } from "@/lib/extraction-service";import { touchPatientSession } from "@/lib/db/cases";
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){
 const s=await getActiveKioskSession();if(!s)return NextResponse.json({error:"No active session"},{status:404});if(!patientWritable(s))return NextResponse.json({error:"Submitted case is read-only"},{status:409});const{id}=await params;
 try{
  const claim=await withKioskTx(s.id,async c=>{const d=await c.query(`SELECT id,ocr_status,extraction_status FROM documents WHERE id=$1 AND session_id=$2 FOR UPDATE`,[id,s.id]);const row=d.rows[0];if(!row)return{kind:"missing" as const};if(row.extraction_status==='COMPLETED'){const existing=await c.query(`SELECT id,category,normalized_value AS "normalizedValue",original_wording AS "originalWording",page_number AS "pageNumber",confidence,uncertainty_notes AS "uncertaintyNotes" FROM clinical_evidence WHERE document_id=$1 ORDER BY created_at`,[id]);return{kind:"complete" as const,items:existing.rows};}if(row.extraction_status==='PROCESSING')return{kind:"busy" as const};if(row.ocr_status!=="COMPLETED")return{kind:"ocr_required" as const};const r=await c.query(`SELECT payload FROM ocr_results WHERE document_id=$1 ORDER BY created_at DESC LIMIT 1`,[id]);await c.query(`UPDATE documents SET processing_status='EXTRACTION_PROCESSING',extraction_status='PROCESSING' WHERE id=$1`,[id]);await touchPatientSession(c,s.id);return{kind:"claimed" as const,pages:r.rows[0]?.payload?.pages??[]};});
  if(claim.kind==="missing")return NextResponse.json({error:"Document not found"},{status:404});if(claim.kind==="busy")return NextResponse.json({error:"Extraction is already running",code:"EXTRACTION_IN_PROGRESS"},{status:409});if(claim.kind==="ocr_required")return NextResponse.json({error:"OCR must complete first"},{status:409});if(claim.kind==="complete")return NextResponse.json({extractionStatus:"COMPLETED",items:claim.items,idempotent:true});
  const drafts=extractEvidence(claim.pages);
  await withKioskTx(s.id,async c=>{await c.query(`DELETE FROM clinical_evidence WHERE document_id=$1 AND extraction_method='DETERMINISTIC' AND verification_state IN('UNVERIFIED','PENDING_REVIEW')`,[id]);await c.query(`DELETE FROM document_extractions WHERE document_id=$1`,[id]);for(const e of drafts)await c.query(`INSERT INTO clinical_evidence(session_id,document_id,category,normalized_value,original_wording,page_number,confidence,extraction_method,provenance,uncertainty_notes,verification_state) VALUES($1,$2,$3,$4,$5,$6,$7,'DETERMINISTIC','OCR',$8,'UNVERIFIED')`,[s.id,id,e.category,JSON.stringify(e.normalizedValue),e.originalWording,e.pageNumber,e.confidence,e.uncertaintyNotes??null]);await c.query(`INSERT INTO document_extractions(document_id,session_id,payload) VALUES($1,$2,$3)`,[id,s.id,JSON.stringify({method:"DETERMINISTIC",itemCount:drafts.length})]);await c.query(`UPDATE documents SET processing_status='EXTRACTION_COMPLETE',extraction_status='COMPLETED',verification_status='PENDING_REVIEW' WHERE id=$1 AND session_id=$2`,[id,s.id]);await touchPatientSession(c,s.id);});
  return NextResponse.json({extractionStatus:"COMPLETED",items:drafts});
 }catch{await withKioskTx(s.id,c=>c.query(`UPDATE documents SET processing_status='FAILED',extraction_status='FAILED' WHERE id=$1 AND session_id=$2 AND extraction_status='PROCESSING'`,[id,s.id]).then(()=>undefined)).catch(()=>{});return NextResponse.json({error:"Extraction failed; physician manual review remains available"},{status:500});}
}
