import { NextResponse } from "next/server";import { getActiveKioskSession,patientWritable } from "@/lib/db/session-scope";import { withKioskTx } from "@/lib/db/pool";import { runOcr } from "@/lib/ocr-service";import { touchPatientSession } from "@/lib/db/cases";
export const runtime="nodejs";
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){
 const s=await getActiveKioskSession();if(!s)return NextResponse.json({error:"No active session"},{status:404});if(!patientWritable(s))return NextResponse.json({error:"Submitted case is read-only"},{status:409});const{id}=await params;
 try{
  const claim=await withKioskTx(s.id,async c=>{const d=await c.query(`SELECT id,mime_type,content,ocr_status FROM documents WHERE id=$1 AND session_id=$2 FOR UPDATE`,[id,s.id]);const row=d.rows[0];if(!row)return{kind:"missing" as const};if(row.ocr_status==='COMPLETED'){const prior=await c.query(`SELECT payload FROM ocr_results WHERE document_id=$1 ORDER BY created_at DESC LIMIT 1`,[id]);return{kind:"complete" as const,pages:prior.rows[0]?.payload?.pages??[]};}if(row.ocr_status==='PROCESSING')return{kind:"busy" as const};await c.query(`UPDATE documents SET processing_status='OCR_PROCESSING',ocr_status='PROCESSING' WHERE id=$1`,[id]);await touchPatientSession(c,s.id);return{kind:"claimed" as const,mimeType:String(row.mime_type),content:Buffer.from(row.content)};});
  if(claim.kind==="missing")return NextResponse.json({error:"Document not found"},{status:404});if(claim.kind==="busy")return NextResponse.json({error:"OCR is already running",code:"OCR_IN_PROGRESS"},{status:409});if(claim.kind==="complete")return NextResponse.json({ocrStatus:"COMPLETED",processingStatus:"OCR_COMPLETE",pages:claim.pages,idempotent:true});
  const pages=await runOcr(claim.content,claim.mimeType,s.language);
  await withKioskTx(s.id,async c=>{await c.query(`DELETE FROM ocr_results WHERE document_id=$1`,[id]);await c.query(`INSERT INTO ocr_results(document_id,session_id,payload) VALUES($1,$2,$3)`,[id,s.id,JSON.stringify({pages,providerMetadata:{provider:"tesseract",language:s.language,createdAt:new Date().toISOString()},handwritingDetected:false})]);await c.query(`UPDATE documents SET processing_status='OCR_COMPLETE',ocr_status='COMPLETED',page_count=$2,errors='[]'::jsonb WHERE id=$1 AND session_id=$3`,[id,pages.length,s.id]);await touchPatientSession(c,s.id);});
  return NextResponse.json({ocrStatus:"COMPLETED",processingStatus:"OCR_COMPLETE",pages});
 }catch{await withKioskTx(s.id,c=>c.query(`UPDATE documents SET processing_status='FAILED',ocr_status='FAILED',errors=errors||$2::jsonb WHERE id=$1 AND session_id=$3 AND ocr_status='PROCESSING'`,[id,JSON.stringify(["OCR processing failed; manual review remains available."]),s.id]).then(()=>undefined)).catch(()=>{});return NextResponse.json({error:"OCR failed; document remains available for manual review"},{status:500});}
}
