"use client";import { useEffect,useState } from "react";import { useRouter } from "next/navigation";import type { Severity } from "@/lib/patient-flow";import { usePatient } from "../PatientShell";
type Row={id:string;position:number;complaintText:string;severity:Severity|null};
const quickSymptoms=["Nausea","Vomiting","Loss of appetite","Bloating","Constipation","Diarrhea","Fever","Fatigue"];
export default function Symptoms(){const r=useRouter();const {sync,mutate,t,saveDraft,loadDraft,clearDraft,queuedBodies}=usePatient();const [items,setItems]=useState<Row[]>([]);const [text,setText]=useState("");const [severity,setSeverity]=useState<Severity|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
async function load(){try{const res=await fetch("/api/patient/complaints",{cache:"no-store"});if(res.ok){const d=await res.json();setItems(d.complaints??[]);return;}}catch{}const queued=await queuedBodies("/api/patient/complaints");const extras=queued.filter(b=>b.primary!==true&&typeof b.complaintText==="string").map((b,i)=>({id:`offline-${String(b.clientMutationId??i)}`,position:2+i,complaintText:String(b.complaintText),severity:(b.severity as Severity|null)??null}));setItems(prev=>{const primary=prev.filter(x=>x.position===1);return[...primary,...extras]});}
useEffect(()=>{void load();void loadDraft<{text:string;severity:Severity|null}>("symptom-draft").then(d=>{if(d){setText(d.text??"");setSeverity(d.severity??null);}})},[]);// eslint-disable-line react-hooks/exhaustive-deps
useEffect(()=>{if(text||severity)void saveDraft("symptom-draft",{text,severity});},[text,severity,saveDraft]);
async function add(value=text){const clean=value.trim();if(!clean||busy)return;setBusy(true);setError("");const mutationId=crypto.randomUUID();const payload={complaintText:clean,severity,clientMutationId:mutationId};const res=await mutate("/api/patient/complaints","POST",payload,mutationId);if(!res.ok){setError("Could not save this symptom. Please retry.");setBusy(false);return;}const optimistic:Row={id:res.queued?`offline-${mutationId}`:String(res.data?.id??mutationId),position:items.length+1,complaintText:clean,severity};setItems(current=>current.some(x=>x.id===optimistic.id)?current:[...current,optimistic]);setText("");setSeverity(null);await clearDraft("symptom-draft");if(!res.queued)await load();setBusy(false);}
async function next(){setBusy(true);if(await sync({workflowStep:"interview"})){r.push("/patient/interview");return;}setBusy(false);}
const saved=items.map(x=>x.complaintText.toLowerCase());const canAdd=items.filter(x=>x.position>1).length<3;
return <section className="flow-card reference-card symptoms-reference-card"><p className="eyebrow">6 · Other symptoms</p><h1>Do you have any of the following symptoms?</h1><p className="lead">Select up to three additional concerns, or describe another symptom in your own words.</p>
<div className="symptom-reference-list">{quickSymptoms.map(label=><button type="button" key={label} disabled={!canAdd||busy||saved.includes(label.toLowerCase())} className="symptom-reference-option" aria-pressed={saved.includes(label.toLowerCase())} onClick={()=>void add(label)}><span>{saved.includes(label.toLowerCase())?"✓":"□"}</span><b>{label}</b></button>)}</div>
{items.length>0&&<div className="saved-symptoms"><strong>Saved for this visit</strong>{items.map(x=><span key={x.id}>{x.position===1?"Main: ":""}{x.complaintText}{x.id.startsWith("offline-")?" · saved offline":""}</span>)}</div>}
{canAdd&&<div className="custom-symptom-card"><div className="field"><label htmlFor="extra">Other symptom</label><textarea id="extra" maxLength={1000} value={text} onChange={e=>setText(e.target.value)} placeholder="Describe another symptom…"/></div><div className="choice-grid compact-severity">{(["MILD","MODERATE","SEVERE","VERY_SEVERE"] as Severity[]).map(s=><button type="button" key={s} className={`choice ${s==="SEVERE"?"severe":s==="VERY_SEVERE"?"very-severe":""}`} aria-pressed={severity===s} onClick={()=>setSeverity(severity===s?null:s)}>{s.replaceAll("_"," ")}</button>)}</div><button type="button" className="secondary full-width" disabled={!text.trim()||busy} onClick={()=>void add()}>+ {busy?"Saving…":"Save symptom"}</button></div>}
{error&&<div className="system-banner error" role="alert">{error}</div>}<div className="reference-actions"><button className="secondary" onClick={()=>r.back()}>← {t("back")}</button><button className="primary reference-primary" disabled={busy} onClick={()=>void next()}>{busy?t("processing"):"Next"} →</button></div></section>}
