"use client";import { useState } from "react";import { useRouter } from "next/navigation";import type { BodyRegion,Severity } from "@/lib/patient-flow";import { usePatient } from "../PatientShell";
const regions:[BodyRegion,string][]=[["head","Head & Neck"],["chest","Chest"],["abdomen","Abdomen"],["back","Back"],["arm","Arms & Hands"],["leg","Legs & Feet"],["skin","Skin"],["other","Other area"]];
const severityOptions:[Severity,string,string][]=[["MILD","Mild","1–3"],["MODERATE","Moderate","4–6"],["SEVERE","Severe","7–8"],["VERY_SEVERE","Very severe","9–10"]];
const hotspot:Record<BodyRegion,[number,number]>={head:[80,42],chest:[80,105],abdomen:[80,145],back:[80,118],arm:[43,122],hand:[30,164],leg:[63,220],foot:[58,286],skin:[100,145],other:[80,175]};
export default function Anatomy(){const r=useRouter();const {workflow,setWorkflow,sync,mutate,t}=usePatient();const [region,setRegion]=useState<BodyRegion|null>(workflow.region);const [severity,setSeverity]=useState<Severity|null>(workflow.severity);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
async function next(){if(busy)return;setBusy(true);setError("");const mapped=await mutate("/api/patient/complaints","PATCH",{primary:true,bodyRegion:region,severity});if(!mapped.ok){setError("Could not save the severity/body area. Please retry.");setBusy(false);return;}const ok=await sync({bodyRegion:region,workflowStep:"symptoms"});if(ok){setWorkflow(w=>({...w,region,severity,currentStep:"symptoms"}));r.push("/patient/symptoms");return;}setBusy(false);}
const point=region?hotspot[region]:null;return <section className="flow-card reference-card anatomy-reference-card"><div className="reference-step-dots" aria-hidden="true"><span>1</span><span>2</span><span>3</span><span>4</span><span className="active">5</span></div><p className="eyebrow">5 · Severity & affected area</p><h1>Rate your pain or discomfort</h1><div className="severity-reference-grid"><button type="button" className="severity-reference none" aria-pressed={severity===null} onClick={()=>setSeverity(null)}><strong>No pain</strong><span>0</span></button>{severityOptions.map(([value,label,range])=><button type="button" key={value} className={`severity-reference ${value.toLowerCase().replaceAll("_","-")}`} aria-pressed={severity===value} onClick={()=>setSeverity(value)}><strong>{label}</strong><span>{range}</span></button>)}</div>
<h2 className="reference-subheading">Select affected area(s)</h2><div className="anatomy-reference-layout"><div className="body-map" aria-hidden="true"><svg viewBox="0 0 160 320" role="img"><circle cx="80" cy="34" r="20"/><path d="M60 58 Q80 50 100 58 L111 118 L99 177 L95 300 L76 300 L72 190 L65 300 L45 300 L50 177 L39 118 Z"/><path d="M48 72 L20 160 L35 166 L62 102 M112 72 L140 160 L125 166 L98 102"/>{point&&<circle className="body-map-hotspot" cx={point[0]} cy={point[1]} r="12"/>}</svg></div><div className="body-region-list">{regions.map(([key,label])=><button type="button" key={key} className="body-region-choice" aria-pressed={region===key} onClick={()=>setRegion(region===key?null:key)}><span>{region===key?"✓":"○"}</span>{label}</button>)}</div></div>
{error&&<div className="system-banner error" role="alert">{error}</div>}<div className="reference-actions"><button className="secondary" onClick={()=>r.back()}>← {t("back")}</button><button className="primary reference-primary" disabled={busy} onClick={()=>void next()}>{busy?t("processing"):"Next"} →</button></div></section>}
